# Arrays and Lists

In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1, 2, 3])

In [5]:
for e in L:
  print(e)

1
2
3


In [6]:
for e in A:
  print(e)

1
2
3


In [7]:
L.append(4)

In [8]:
L

[1, 2, 3, 4]

In [10]:
A.append(4)

AttributeError: ignored

In [12]:
L + [5]

[1, 2, 3, 4, 5]

In [14]:
A + np.array([4])

array([5, 6, 7])

In [16]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [18]:
A + np.array([4, 5])

ValueError: ignored

In [22]:
2 * A

array([2, 4, 6])

In [24]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [25]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [26]:
L2 = []
for e in L:
  L2.append(e + 3)

In [27]:
L2

[4, 5, 6, 7]

In [30]:
L2 = [e + 3 for e in L]
L2

[4, 5, 6, 7]

In [31]:
L ** 2

TypeError: ignored

In [34]:
L2 = []
for e in L:
  L2.append(e ** 2)

In [35]:
L2

[1, 4, 9, 16]

In [36]:
A ** 2

array([1, 4, 9])

In [37]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [38]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [39]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [40]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [44]:
a = np.array([1, 2])
b = np.array([3, 4])

In [45]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

In [46]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [47]:
a * b

array([3, 8])

In [48]:
np.sum(a * b)

11

In [49]:
(a * b).sum()

11

In [51]:
np.dot(a, b)

11

In [52]:
a.dot(b)

11

In [53]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [54]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [56]:
np.linalg.norm(a)

2.23606797749979

In [58]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [60]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

# Speed Test

In [61]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 29.913386322169327


# Matrices

In [62]:
L = [[1, 2], [3, 4]]
L

[[1, 2], [3, 4]]

In [63]:
L[0]

[1, 2]

In [64]:
L[0][1]

2

In [66]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [68]:
A[0][1]

2

In [69]:
A[0, 1]

2

In [70]:
A[:, 0]

array([1, 3])

In [71]:
A.T

array([[1, 3],
       [2, 4]])

In [72]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [73]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [74]:
B = np.array([[1, 2, 3], [4, 5, 6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [76]:
A.dot(B.T)

ValueError: ignored

In [77]:
np.linalg.det(A)

-2.0000000000000004

In [79]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [82]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [83]:
np.trace(A)

5

In [84]:
np.diag(A)

array([1, 4])

In [85]:
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

In [86]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [87]:
Lam, V = np.linalg.eig(A)

In [89]:
V[:, 0] * Lam[0], A @ V[:, 0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [90]:
np.allclose(V[:, 0] * Lam[0], A @ V[:, 0])

True

In [91]:
np.allclose(V @ np.diag(Lam), A @ V)

True

# Solving Linear Systems

$$ x_1 + x_2 = 2200\\
  1.5 x_1 + 4x_2 = 5050$$

In [93]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [94]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [95]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

# Generating Data

In [136]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [137]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [138]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [139]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
np.random.random()

0.9907841303765829

In [141]:
np.random.random((2, 3))

array([[0.37362213, 0.20334945, 0.48906819],
       [0.83794881, 0.24067796, 0.30204701]])

In [142]:
np.random.randn(2, 3)

array([[-0.58517931,  1.0869928 , -1.72312464],
       [ 1.47023392, -1.24049534, -0.81159827]])

In [143]:
R = np.random.randn(10000)

In [144]:
R.mean()

-0.006440442947581336

In [145]:
np.mean(R)

-0.006440442947581336

In [146]:
R.var()

1.0072391136528975

In [147]:
R.std()

1.0036130298341575

In [148]:
R = np.random.randn(10000, 3)

In [149]:
R.mean(axis=0)

array([-0.01988795,  0.01663651, -0.00196971])

In [150]:
R.mean(axis=1).shape

(10000,)

In [151]:
np.cov(R).shape

(10000, 10000)

In [152]:
np.cov(R.T)

array([[ 0.98087383, -0.00921347, -0.00369223],
       [-0.00921347,  1.00629361,  0.0015555 ],
       [-0.00369223,  0.0015555 ,  1.01124892]])

In [153]:
np.cov(R, rowvar=False)

array([[ 0.98087383, -0.00921347, -0.00369223],
       [-0.00921347,  1.00629361,  0.0015555 ],
       [-0.00369223,  0.0015555 ,  1.01124892]])

In [154]:
np.random.randint(0, 10, size=(3, 3))

array([[4, 1, 7],
       [9, 5, 0],
       [6, 5, 0]])

In [155]:
np.random.choice(10, size=(3, 3))

array([[3, 7, 0],
       [4, 6, 3],
       [1, 9, 6]])